### ISSUE TITLE
Error when running sample code

### ISSUE THREAD

**Issue by AnnaSou** [ewsheng/nlg-bias#4]
Hello @ewsheng,

I am trying to run the sample code following the instructions, but getting this error:

```
(biases) -bash-4.2$ python scripts/eval.py --sample_file data/generated_samples/sample.tsv --model_type regard2
params Namespace(model_type='regard2', sample_file='data/generated_samples/sample.tsv')
Model type: regard2
No ext sample name: data/generated_samples/sample
Labeling with first classifier...
11/16/2020 13:31:38 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
scripts/run_ensemble.sh: line 61:  1330 Segmentation fault      (core dumped) python scripts/run_classifier.py --data_dir ${DATA_DIR} --model_type bert --model_name_or_path ${BERT_MODEL1} --output_dir ${OUTPUT_DIR} --max_seq_length ${MAX_LENGTH} --do_predict --test_file ${TEST_FILE} --do_lower_case --overwrite_cache --per_gpu_eval_batch_size 32 --model_version ${MODEL_VERSION}
Labeling with second classifier...
11/16/2020 13:31:45 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
scripts/run_ensemble.sh: line 74:  1364 Segmentation fault      (core dumped) python scripts/run_classifier.py --data_dir ${DATA_DIR} --model_type bert --model_name_or_path ${BERT_MODEL2} --output_dir ${OUTPUT_DIR}_2 --max_seq_length ${MAX_LENGTH} --do_predict --test_file ${TEST_FILE} --do_lower_case --overwrite_cache --per_gpu_eval_batch_size 32 --model_version ${MODEL_VERSION}
Labeling with third classifier...
11/16/2020 13:31:47 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
scripts/run_ensemble.sh: line 87:  1382 Segmentation fault      (core dumped) python scripts/run_classifier.py --data_dir ${DATA_DIR} --model_type bert --model_name_or_path ${BERT_MODEL3} --output_dir ${OUTPUT_DIR}_3 --max_seq_length ${MAX_LENGTH} --do_predict --test_file ${TEST_FILE} --do_lower_case --overwrite_cache --per_gpu_eval_batch_size 32 --model_version ${MODEL_VERSION}
Collecting majority labels...
cp: cannot stat ‘models/bert_regard_v2/sample_predictions.txt’: No such file or directory
cp: cannot stat ‘models/bert_regard_v2_2/sample_predictions.txt’: No such file or directory
cp: cannot stat ‘models/bert_regard_v2_3/sample_predictions.txt’: No such file or directory
Done!
================================================================================
RESPECT
Traceback (most recent call last):
  File "scripts/analyze_generated_outputs.py", line 17, in <module>
    import matplotlib.pyplot as plt
  File "/fs/clip-scratch/annasout/miniconda3/envs/biases/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/fs/clip-scratch/annasout/miniconda3/envs/biases/lib/python3.7/site-packages/matplotlib/pyplot.py", line 287, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
================================================================================
OCCUPATION
Traceback (most recent call last):
  File "scripts/analyze_generated_outputs.py", line 17, in <module>
    import matplotlib.pyplot as plt
  File "/fs/clip-scratch/annasout/miniconda3/envs/biases/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/fs/clip-scratch/annasout/miniconda3/envs/biases/lib/python3.7/site-packages/matplotlib/pyplot.py", line 287, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

```

Thanks,
Anna

**Comment by ewsheng** [comment]
Hi @AnnaSou,

I'm not sure why you're getting a segmentation fault in ```run_classifier.py``` based on the error message alone. Could you maybe try running the```run_classifier.py```  command in ```run_ensemble.sh``` directly for a more detailed error message? As for the import errors that follow, you can just comment out the import statement and related code to get rid of the errors (it won't create the bar charts, but it should still print the related numbers).

**Comment by AnnaSou** [comment]
I think I fixed the error: there was a version problem. Thanks!
